version: '3.8'

services:
  pokedex-api:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8086:8080"
    depends_on:
      - hydra-admin
      - hydra-public
    environment:
      - Authentication__Authority=http://hydra-public:4444/
      - Authentication__Issuer=http://hydra-public:4444/
      - TrainerApiEndpoint=http://host.docker.internal:8098
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: hydra
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: hydra
    ports:
      - "5432:5432"
    volumes:
      - hydra-data:/var/lib/postgresql/data

  hydra-admin:
    image: oryd/hydra:v2.2
    depends_on:
      - postgres
      - hydra-migrate
    environment:
      - DSN=postgres://hydra:secret@postgres:5432/hydra?sslmode=disable
      - URLS_SELF_ISSUER=http://hydra-public:4444
      - SECRETS_SYSTEM=thisisaverysecretkey123
      - LOG_LEVEL=debug
    command: serve admin --dev
    ports:
      - "4445:4445"

  hydra-public:
    image: oryd/hydra:v2.2
    depends_on:
      - postgres
      - hydra-migrate
    environment:
      - DSN=postgres://hydra:secret@postgres:5432/hydra?sslmode=disable
      - URLS_SELF_ISSUER=http://hydra-public:4444
      - SECRETS_SYSTEM=thisisaverysecretkey123
      - OAUTH2_EXPOSE_INTERNAL_ERRORS=true
      - LOG_LEVEL=debug
    command: serve public --dev
    ports:
      - "4444:4444"
  hydra-migrate:
    image: oryd/hydra:v2.2
    depends_on:
      - postgres
    environment:
      - DSN=postgres://hydra:secret@postgres:5432/hydra?sslmode=disable
    command: migrate sql -e --yes

networks:
  default:
    name: "hydra-net"
volumes:
  hydra-data: